
language: python
dist: trusty
sudo: required

os:
  - linux
# - osx
  
install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
       brew update > /dev/null
    && brew install qt5 > /dev/null
    && export PATH=/usr/local/opt/qt5/bin/:$PATH
    ;
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       sudo add-apt-repository --yes ppa:beineri/opt-qt592-trusty &&
       sudo apt-get update -y &&
       sudo apt-get install qt59base -y &&
       source /opt/qt59/bin/qt59-env.sh
       ; 
  fi
- cd ./3rdparty && ./build.sh && cd ./../
- qmake -v
script:
  - git submodule update --init --recursive 
  - cd ./tests
